import React, { useEffect, useMemo, useState } from "react";

const CASES = [
  { id: "rr_84721", customer: "Rohan Mehta", initials: "RM", segment: "Payment failure", channel: "UPI", amount: 2490, risk: "high", cause: "Bank timeout after authentication", diagnosis: "Transient issuer failure", confidence: 94, action: "Retry via alternate acquirer", next: "Retry once in 10 min", status: "in_progress", time: "2 min ago", color: "teal", steps: ["Detected", "Diagnosed", "Retry queued", "Awaiting outcome"], audit: [["09:42:18", "Signal detected", "Payment declined · bank timeout"], ["09:42:19", "Agent decision", "Transient failure, 94% confidence"], ["09:42:19", "Guardrail check", "Retry 1 of 2 allowed"], ["09:42:20", "Action queued", "Alternate acquirer · +10 min"]] },
  { id: "rr_84718", customer: "Ayesha Khan", initials: "AK", segment: "Checkout drop-off", channel: "Web checkout", amount: 6800, risk: "high", cause: "Cart idle after payment method selection", diagnosis: "Friction at final confirmation", confidence: 87, action: "Send one-tap checkout link", next: "SMS queued · expires in 24h", status: "in_progress", time: "5 min ago", color: "coral", steps: ["Detected", "Diagnosed", "Link sent", "Awaiting payment"], audit: [["09:39:04", "Signal detected", "Checkout idle for 18 minutes"], ["09:39:05", "Agent decision", "High intent, 87% confidence"], ["09:39:05", "Guardrail check", "One nudge permitted"], ["09:39:06", "Action sent", "Personalized SMS with payment link"]] },
  { id: "rr_84711", customer: "Northstar Labs", initials: "NL", segment: "Overdue receivable", channel: "Invoice · Net 30", amount: 48500, risk: "medium", cause: "Invoice 9 days past due", diagnosis: "No dispute signal found", confidence: 79, action: "Send friendly payment reminder", next: "Email sent · follow up in 3 days", status: "recovered", time: "12 min ago", color: "amber", steps: ["Detected", "Diagnosed", "Reminder sent", "Paid in full"], audit: [["09:31:11", "Signal detected", "Invoice crossed due date +9d"], ["09:31:12", "Agent decision", "Low-friction reminder selected"], ["09:31:12", "Guardrail check", "No escalation before +14d"], ["09:38:44", "Outcome confirmed", "₹48,500 received"]] },
  { id: "rr_84703", customer: "Maya Iyer", initials: "MI", segment: "Failed subscription", channel: "Visa ending 4821", amount: 1299, risk: "medium", cause: "Insufficient funds on renewal", diagnosis: "Likely temporary balance gap", confidence: 71, action: "Retry after salary-window signal", next: "Retry scheduled · tomorrow 09:00", status: "scheduled", time: "18 min ago", color: "amber", steps: ["Detected", "Diagnosed", "Retry scheduled", "Awaiting outcome"], audit: [["09:25:52", "Signal detected", "Renewal declined · insufficient funds"], ["09:25:53", "Agent decision", "Delay improves recovery odds"], ["09:25:53", "Guardrail check", "Max 2 retries per renewal"], ["09:25:54", "Action scheduled", "Tomorrow at 09:00 local time"]] },
  { id: "rr_84698", customer: "Dev Patel", initials: "DP", segment: "Payment failure", channel: "Credit card", amount: 9200, risk: "blocked", cause: "Issuer risk block", diagnosis: "Not safe to retry automatically", confidence: 96, action: "Stop automation and request review", next: "Manual review required", status: "stopped", time: "26 min ago", color: "red", steps: ["Detected", "Diagnosed", "Automation stopped", "Manual review"], audit: [["09:17:31", "Signal detected", "Declined by issuer risk engine"], ["09:17:32", "Agent decision", "Risk block, 96% confidence"], ["09:17:32", "Guardrail check", "Automatic retry prohibited"], ["09:17:33", "Action stopped", "Case routed to risk operations"]] },
];

const FILTERS = ["All signals", "Payments", "Checkout", "Subscriptions", "Receivables"];
function formatINR(value) { return `₹${value.toLocaleString("en-IN")}`; }
function statusLabel(status) { return { in_progress: "In progress", recovered: "Recovered", scheduled: "Scheduled", stopped: "Stopped" }[status]; }
function createBatchCases() {
  const batchId = Date.now().toString(36);
  const templates = [
    ["Tara Shah", "TS", "Checkout drop-off", "Web checkout", 3790, "Cart idle after address step", "High-intent checkout friction", 84, "Send one-tap checkout link", "SMS queued · expires in 24h", "in_progress", "coral", ["Detected", "Diagnosed", "Link sent", "Awaiting payment"]],
    ["Orbit Systems", "OS", "Overdue receivable", "Invoice · Net 15", 27500, "Invoice 6 days past due", "No dispute signal found", 82, "Send friendly payment reminder", "Email sent · follow up in 3 days", "recovered", "amber", ["Detected", "Diagnosed", "Reminder sent", "Paid in full"]],
    ["Kabir Rao", "KR", "Failed subscription", "Mastercard ending 1904", 1899, "Insufficient funds on renewal", "Temporary balance gap likely", 73, "Retry after salary-window signal", "Retry scheduled · tomorrow 09:00", "scheduled", "amber", ["Detected", "Diagnosed", "Retry scheduled", "Awaiting outcome"]],
    ["Nisha Verma", "NV", "Payment failure", "Credit card", 5400, "Issuer risk block", "Not safe to retry automatically", 95, "Stop automation and request review", "Manual review required", "stopped", "red", ["Detected", "Diagnosed", "Automation stopped", "Manual review"]],
  ];
  return templates.map(([customer, initials, segment, channel, amount, cause, diagnosis, confidence, action, next, status, color, steps], index) => ({
    id: `rr_${batchId}_${index}`,
    customer, initials, segment, channel, amount, risk: status === "stopped" ? "blocked" : status === "recovered" ? "medium" : "high", cause, diagnosis, confidence, action, next, status, time: "just now", color, steps,
    audit: [["now", "Signal detected", cause], ["now", "Agent decision", `${diagnosis} · ${confidence}% confidence`], ["now", "Guardrail check", status === "stopped" ? "Automatic retry prohibited" : "Action within policy limits"], ["now", status === "recovered" ? "Outcome confirmed" : status === "stopped" ? "Action stopped" : "Action queued", next]],
  }));
}

function App() {
  const [cases, setCases] = useState(CASES);
  const [selectedId, setSelectedId] = useState(CASES[0].id);
  const [filter, setFilter] = useState("All signals");
  const [running, setRunning] = useState(true);
  const [toast, setToast] = useState("");
  useEffect(() => { if (!toast) return undefined; const timer = setTimeout(() => setToast(""), 2800); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => {
    if (!running) return undefined;
    const timer = setInterval(() => {
      const liveCase = createBatchCases()[0];
      setCases((currentCases) => [liveCase, ...currentCases].slice(0, 12));
      setToast(`New ${liveCase.segment.toLowerCase()} signal processed.`);
    }, 8000);
    return () => clearInterval(timer);
  }, [running]);
  const filteredCases = useMemo(() => { if (filter === "All signals") return cases; const lookup = { Payments: "Payment failure", Checkout: "Checkout drop-off", Subscriptions: "Failed subscription", Receivables: "Overdue receivable" }; return cases.filter((item) => item.segment === lookup[filter]); }, [cases, filter]);
  const selected = cases.find((item) => item.id === selectedId) || cases[0];
  const recovered = cases.filter((item) => item.status === "recovered").reduce((sum, item) => sum + item.amount, 0);
  const atRisk = cases.filter((item) => item.status !== "recovered" && item.status !== "stopped").reduce((sum, item) => sum + item.amount, 0);
  const active = cases.filter((item) => item.status === "in_progress" || item.status === "scheduled").length;
  function runBatch() {
    setRunning(true);
    setToast("Recovery agent is scanning new signals...");
    setTimeout(() => {
      const newCases = createBatchCases();
      setCases((currentCases) => [...newCases, ...currentCases].slice(0, 12));
      setSelectedId(newCases[0].id);
      setToast("Batch complete: 4 new signals processed, 1 case stopped by guardrails.");
    }, 1300);
  }
  function pauseAgent() { setRunning((value) => !value); setToast(running ? "Live interventions paused. Detection remains on." : "Live interventions resumed."); }
  return <main className="app-shell">
    <header className="topbar"><div className="brand-block"><div className="brand-mark">↗</div><div><div className="brand-name">recover / agent</div><div className="brand-context">Revenue recovery operations</div></div></div><div className="top-actions"><div className={`live-status ${running ? "is-live" : "is-paused"}`}><span /> {running ? "Agent live" : "Agent paused"}</div><button className="button quiet" onClick={pauseAgent}>{running ? "Pause" : "Resume"}</button><button className="button primary" onClick={runBatch}>Run batch <span>→</span></button></div></header>
    <section className="intro-row"><div><p className="eyebrow">Tuesday · 04 September 2026 · 09:44 IST</p><h1>Find the money before it disappears.</h1><p className="intro-copy">Detect revenue risk, choose the least intrusive intervention, and stop when the evidence says to stop.</p></div><div className="batch-note"><span><i className="pulse" /> Last batch completed <strong>42 sec ago</strong></span><span>1,284 signals · 68 interventions · 7.8% recovered</span></div></section>
    <section className="metric-grid"><MetricCard label="Recovered this batch" value={formatINR(recovered)} detail="+18.4% vs previous batch" tone="teal" /><MetricCard label="Recovery rate" value="7.8%" detail="94 of 1,202 eligible cases" tone="coral" /><MetricCard label="Revenue at risk" value={formatINR(atRisk)} detail="Across 26 open cases" tone="amber" /><MetricCard label="Active interventions" value={String(active)} detail="All within policy limits" tone="ink" /></section>
    <section className="workspace"><aside className="signal-panel"><div className="panel-heading"><div><p className="eyebrow">Live queue</p><h2>Signals at risk <span>{cases.length}</span></h2></div><button className="icon-button" title="Refresh signals" onClick={() => setToast("Signal queue refreshed.")}>↻</button></div><div className="filter-row">{FILTERS.map((item) => <button key={item} className={filter === item ? "filter active" : "filter"} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="signal-list">{filteredCases.map((item) => <SignalRow key={item.id} item={item} selected={selectedId === item.id} onClick={() => setSelectedId(item.id)} />)}</div><div className="queue-footer"><span className="mini-dot" /> Listening to payment, checkout, subscription and invoice events</div></aside>
      <section className="case-panel"><div className="case-topline"><div><p className="eyebrow">Selected case · {selected.id}</p><h2>{selected.customer}</h2></div><span className={`risk-tag ${selected.risk}`}>{selected.risk === "blocked" ? "Automation stopped" : `${selected.risk} recovery risk`}</span></div><div className="case-value"><span>{formatINR(selected.amount)}</span><span className="case-meta">{selected.segment} · {selected.channel}</span></div><div className="workflow-card"><div className="card-heading"><div><p className="eyebrow">Bounded recovery workflow</p><h3>{selected.action}</h3></div><span className={`confidence ${selected.color}`}>{selected.confidence}% confidence</span></div><div className="workflow-steps">{selected.steps.map((step, index) => <div className={`workflow-step ${index < 3 || selected.status === "recovered" ? "complete" : "current"}`} key={step}><span className="step-number">{index < 3 || selected.status === "recovered" ? "✓" : index + 1}</span><span>{step}</span></div>)}</div><div className="decision-grid"><div><span className="label">Diagnosis</span><strong>{selected.diagnosis}</strong></div><div><span className="label">Next action</span><strong>{selected.next}</strong></div></div></div><div className="lower-grid"><div className="reasoning"><p className="eyebrow">Why this intervention</p><p>Signals point to a recoverable event, so the agent selected the smallest action likely to restore payment without adding customer friction.</p><div className="signal-chips"><span>+ issuer response</span><span>+ customer intent</span><span>− no dispute</span></div></div><div className="guardrail"><p className="eyebrow">Stopping rules</p><div><span className="guardrail-check">✓</span> Max 2 retries per payment</div><div><span className="guardrail-check">✓</span> One customer nudge per 24h</div><div><span className="guardrail-check">✓</span> Stop on risk or dispute signal</div></div></div></section>
      <aside className="audit-panel"><div className="panel-heading"><div><p className="eyebrow">Traceability</p><h2>Audit trail</h2></div><span className="audit-count">{selected.audit.length} events</span></div><div className="audit-list">{selected.audit.map(([time, title, detail]) => <div className="audit-event" key={`${time}-${title}`}><span className="audit-time">{time}</span><div className="audit-line"><span className="audit-node" /><div><strong>{title}</strong><p>{detail}</p></div></div></div>)}</div><div className="compliance-note"><span>⌁</span><div><strong>Compliant by default</strong><p>Every action is explainable, reversible where possible, and logged before execution.</p></div></div></aside></section>
    {toast && <div className="toast">{toast}</div>}
  </main>;
}
function MetricCard({ label, value, detail, tone }) { return <div className={`metric-card ${tone}`}><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-detail">{detail}</div></div>; }
function SignalRow({ item, selected, onClick }) { return <button className={`signal-row ${selected ? "selected" : ""}`} onClick={onClick}><div className="signal-row-top"><span className="avatar">{item.initials}</span><span className="customer">{item.customer}</span><span className="amount">{formatINR(item.amount)}</span></div><div className="signal-row-bottom"><span className={`signal-type ${item.color}`}>{item.segment}</span><span>{item.time}</span><span className={`status ${item.status}`}>{statusLabel(item.status)}</span></div></button>; }

const globalCss = `
@import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap');
:root { font-family: 'Manrope', sans-serif; color: #202522; background: #e9e6de; font-synthesis: none; } * { box-sizing: border-box; } body { margin: 0; min-width: 320px; } button { font: inherit; } button:focus-visible { outline: 3px solid #e45f48; outline-offset: 2px; }
.app-shell { min-height: 100vh; background: radial-gradient(circle at 85% 0%, #f5cdb8 0, transparent 27%), #e9e6de; padding: 0 32px 32px; } .topbar { height: 76px; display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #c8c7bc; } .brand-block, .top-actions, .live-status, .signal-row-top, .signal-row-bottom, .panel-heading, .card-heading { display: flex; align-items: center; } .brand-block { gap: 11px; } .brand-mark { width: 32px; height: 32px; display: grid; place-items: center; background: #202522; color: #f5cdb8; font-size: 20px; font-weight: 800; } .brand-name { font-size: 14px; font-weight: 800; letter-spacing: -.03em; } .brand-context, .eyebrow, .metric-detail, .case-meta, .queue-footer, .audit-time { color: #777b72; } .brand-context { font-size: 10px; margin-top: 3px; font-family: 'DM Mono', monospace; } .top-actions { gap: 10px; } .live-status { gap: 7px; margin-right: 8px; font-size: 11px; font-family: 'DM Mono', monospace; } .live-status span, .pulse, .mini-dot { width: 7px; height: 7px; border-radius: 50%; background: #1a8f6a; display: inline-block; box-shadow: 0 0 0 4px #c7e6da; } .is-paused span { background: #b57923; box-shadow: 0 0 0 4px #f0dfbc; } .button { border: 1px solid #bfc0b6; background: transparent; padding: 9px 14px; font-size: 11px; font-weight: 700; cursor: pointer; } .button.primary { background: #202522; color: #fffaf0; border-color: #202522; } .button.primary span { color: #f5a58c; padding-left: 8px; }
.intro-row { display: flex; justify-content: space-between; align-items: end; padding: 44px 0 32px; gap: 32px; } .eyebrow { margin: 0 0 8px; font: 10px 'DM Mono', monospace; letter-spacing: .08em; text-transform: uppercase; } h1, h2, h3, p { margin-top: 0; } h1 { max-width: 660px; margin-bottom: 12px; font-size: clamp(30px, 4vw, 52px); line-height: 1.05; letter-spacing: -.06em; } .intro-copy { color: #62675f; font-size: 14px; max-width: 560px; line-height: 1.6; margin-bottom: 0; } .batch-note { min-width: 280px; padding: 14px 16px; border-left: 2px solid #e45f48; font: 11px 'DM Mono', monospace; line-height: 1.5; } .batch-note span { display: block; } .batch-note span:last-child { color: #777b72; padding-left: 12px; margin-top: 6px; } .batch-note .pulse { margin-right: 5px; width: 6px; height: 6px; box-shadow: none; vertical-align: middle; }
.metric-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 16px; } .metric-card { min-height: 132px; padding: 18px 20px; border: 1px solid #d1d0c5; background: rgba(255, 252, 245, .55); position: relative; overflow: hidden; } .metric-card:after { content: ''; position: absolute; width: 110px; height: 110px; border: 1px solid currentColor; border-radius: 50%; right: -45px; bottom: -66px; opacity: .18; } .metric-card.teal { color: #157c5c; } .metric-card.coral { color: #d95f49; } .metric-card.amber { color: #a46b1f; } .metric-card.ink { color: #202522; } .metric-label { font-size: 11px; color: #70756c; } .metric-value { margin: 16px 0 4px; color: #202522; font-size: 28px; font-weight: 800; letter-spacing: -.05em; } .metric-detail { font-size: 10px; font-family: 'DM Mono', monospace; }
.workspace { display: grid; grid-template-columns: minmax(270px, 28%) minmax(400px, 1fr) minmax(250px, 25%); border: 1px solid #c8c7bc; background: rgba(255, 252, 245, .38); min-height: 620px; } .signal-panel, .case-panel, .audit-panel { min-width: 0; } .signal-panel, .audit-panel { background: rgba(245, 242, 233, .66); } .signal-panel { border-right: 1px solid #c8c7bc; } .audit-panel { border-left: 1px solid #c8c7bc; } .panel-heading { justify-content: space-between; padding: 20px 20px 14px; align-items: flex-start; } .panel-heading h2, .case-topline h2 { font-size: 18px; letter-spacing: -.04em; margin-bottom: 0; } .panel-heading h2 span { color: #a2a39a; font: 12px 'DM Mono', monospace; margin-left: 5px; } .icon-button { border: 0; background: transparent; cursor: pointer; color: #767b72; font-size: 20px; } .filter-row { display: flex; gap: 5px; overflow-x: auto; padding: 0 20px 14px; border-bottom: 1px solid #d2d0c6; } .filter { border: 1px solid #d0cec4; background: transparent; padding: 6px 8px; white-space: nowrap; color: #777b72; font-size: 10px; cursor: pointer; } .filter.active { background: #202522; border-color: #202522; color: #fffaf0; } .signal-list { padding: 5px 8px; } .signal-row { width: 100%; padding: 13px 12px; text-align: left; border: 0; border-bottom: 1px solid #d8d6cc; background: transparent; color: #202522; cursor: pointer; } .signal-row.selected { background: #fffaf0; box-shadow: inset 3px 0 #e45f48; } .signal-row-top { gap: 8px; } .avatar { width: 25px; height: 25px; display: grid; place-items: center; background: #dddcd2; color: #5e625a; font: 9px 'DM Mono', monospace; } .customer { font-size: 12px; font-weight: 700; } .amount { margin-left: auto; font: 11px 'DM Mono', monospace; } .signal-row-bottom { margin: 8px 0 0 33px; gap: 7px; color: #898b83; font: 9px 'DM Mono', monospace; } .signal-type { font-family: 'Manrope', sans-serif; font-weight: 700; } .signal-type.teal { color: #188263; } .signal-type.coral { color: #d95f49; } .signal-type.amber { color: #a46b1f; } .signal-type.red { color: #bd4e4c; } .status { margin-left: auto; } .status.recovered { color: #188263; } .status.stopped { color: #bd4e4c; } .queue-footer { padding: 15px 20px; border-top: 1px solid #d2d0c6; font: 9px 'DM Mono', monospace; line-height: 1.6; } .mini-dot { width: 5px; height: 5px; margin-right: 6px; box-shadow: none; }
.case-panel { padding: 24px 28px; background: rgba(255, 252, 245, .5); } .case-topline { display: flex; justify-content: space-between; gap: 16px; align-items: flex-start; } .risk-tag, .confidence { display: inline-block; padding: 6px 8px; font: 9px 'DM Mono', monospace; text-transform: uppercase; letter-spacing: .04em; } .risk-tag.high { color: #c6503e; background: #f9dbd0; } .risk-tag.medium { color: #946019; background: #f3e3c0; } .risk-tag.blocked { color: #a73e3e; background: #f4d2d2; } .case-value { display: flex; align-items: baseline; gap: 10px; margin: 20px 0 25px; } .case-value > span:first-child { font-size: 32px; font-weight: 800; letter-spacing: -.06em; } .case-meta { font: 10px 'DM Mono', monospace; } .workflow-card { padding: 19px; border: 1px solid #cbc9bf; background: #fffaf0; } .card-heading { justify-content: space-between; gap: 12px; align-items: flex-start; } .card-heading h3 { font-size: 16px; letter-spacing: -.03em; margin-bottom: 0; } .confidence { color: #188263; background: #d9eee5; } .confidence.coral { color: #c6503e; background: #f9dbd0; } .confidence.amber { color: #946019; background: #f3e3c0; } .confidence.red { color: #a73e3e; background: #f4d2d2; } .workflow-steps { display: grid; grid-template-columns: repeat(4, 1fr); gap: 6px; margin: 28px 0 24px; } .workflow-step { display: flex; align-items: center; gap: 7px; color: #96988f; font-size: 10px; line-height: 1.3; } .workflow-step.complete { color: #202522; } .step-number { display: grid; place-items: center; width: 20px; height: 20px; border-radius: 50%; border: 1px solid #c4c4b9; flex-shrink: 0; font: 9px 'DM Mono', monospace; } .complete .step-number { border-color: #188263; background: #188263; color: white; } .decision-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; border-top: 1px solid #dfddd3; padding-top: 15px; } .decision-grid div { display: flex; flex-direction: column; gap: 6px; } .label { color: #858980; font: 9px 'DM Mono', monospace; text-transform: uppercase; } .decision-grid strong { font-size: 12px; line-height: 1.45; }
.lower-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-top: 10px; } .reasoning, .guardrail { padding: 17px; border: 1px solid #d4d2c8; } .reasoning p:not(.eyebrow) { color: #62675f; font-size: 11px; line-height: 1.6; margin-bottom: 14px; } .signal-chips { display: flex; gap: 5px; flex-wrap: wrap; } .signal-chips span { padding: 5px 7px; background: #e8e6dc; color: #70756c; font: 9px 'DM Mono', monospace; } .guardrail { background: #f1f0e8; } .guardrail > div { font-size: 10px; margin: 9px 0; } .guardrail-check { color: #188263; font-weight: 800; padding-right: 7px; } .audit-panel { padding-bottom: 20px; } .audit-count { color: #777b72; font: 9px 'DM Mono', monospace; } .audit-list { padding: 3px 20px 20px; } .audit-event { display: grid; grid-template-columns: 52px 1fr; gap: 8px; min-height: 65px; } .audit-time { font: 9px 'DM Mono', monospace; padding-top: 2px; } .audit-line { display: flex; gap: 10px; position: relative; } .audit-line:before { content: ''; position: absolute; left: 4px; top: 13px; bottom: -23px; width: 1px; background: #d0cec4; } .audit-event:last-child .audit-line:before { display: none; } .audit-node { width: 9px; height: 9px; margin-top: 3px; border-radius: 50%; border: 2px solid #188263; background: #f5f2e9; z-index: 1; flex-shrink: 0; } .audit-line strong { font-size: 10px; } .audit-line p { margin: 4px 0 0; color: #777b72; font-size: 10px; line-height: 1.4; } .compliance-note { display: flex; gap: 10px; margin: 4px 20px 0; padding: 13px; background: #e0eee6; color: #23664f; } .compliance-note > span { font-size: 20px; } .compliance-note strong { font-size: 10px; } .compliance-note p { margin: 4px 0 0; color: #4d806c; font-size: 9px; line-height: 1.5; } .toast { position: fixed; right: 28px; bottom: 24px; padding: 13px 16px; background: #202522; color: #fffaf0; box-shadow: 0 10px 30px #20252230; font: 10px 'DM Mono', monospace; }
@media (max-width: 1050px) { .workspace { grid-template-columns: minmax(260px, 34%) 1fr; } .audit-panel { grid-column: 1 / -1; border-left: 0; border-top: 1px solid #c8c7bc; } .audit-list { display: grid; grid-template-columns: repeat(4, 1fr); } .audit-event { min-height: 80px; } .intro-row { align-items: flex-start; flex-direction: column; } .batch-note { align-self: stretch; } } @media (max-width: 720px) { .app-shell { padding: 0 16px 20px; } .topbar { height: auto; padding: 16px 0; align-items: flex-start; gap: 14px; flex-direction: column; } .top-actions { width: 100%; } .top-actions .button { flex: 1; } .live-status { margin-right: auto; } .intro-row { padding: 30px 0 24px; } .metric-grid { grid-template-columns: 1fr 1fr; } .metric-card { min-height: 115px; padding: 14px; } .metric-value { font-size: 22px; } .workspace { display: block; } .signal-panel { border-right: 0; border-bottom: 1px solid #c8c7bc; } .case-panel { padding: 22px 16px; } .audit-panel { border-top: 1px solid #c8c7bc; } .audit-list { display: block; } .workflow-steps { grid-template-columns: repeat(2, 1fr); row-gap: 14px; } .lower-grid { grid-template-columns: 1fr; } .case-topline { flex-direction: column; } .batch-note { min-width: 0; width: 100%; } }
`;

export default function StyledApp() { return <><style>{globalCss}</style><App /></>; }
